-- CreateTable
CREATE TABLE "team" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "photo" STRING NOT NULL,
    "description" STRING NOT NULL,

    CONSTRAINT "team_pkey" PRIMARY KEY ("id")
);
